---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/dncurs82/doceflow.xd360.com.br/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp public/.htaccess $DEPLOYPATH/public/
    - test -f $DEPLOYPATH/.env || /bin/cp .env.example $DEPLOYPATH/.env
